### ISSUE TITLE
Flaky package dependency tests

### ISSUE THREAD

**Issue by award999** [swiftlang/vscode-swift#1258]
Some package dependency tests are flaky in CI
```
  1) PackageDependencyProvider Test Suite
       Includes local dependency:
     AssertionError: Expected to find defaultPackage, but instead items were swift-cmark,swift-markdown: expected undefined not to be undefined
      at Context.<anonymous> (d:\a\vscode-swift\vscode-swift\test\integration-tests\ui\PackageDependencyProvider.test.ts:65:20)

  2) PackageDependencyProvider Test Suite
       Lists local dependency file structure:
     AssertionError: Expected to find defaultPackage, but instead items were swift-cmark,swift-markdown: expected undefined not to be undefined
      at Context.<anonymous> (d:\a\vscode-swift\vscode-swift\test\integration-tests\ui\PackageDependencyProvider.test.ts:77:20)
```

**Comment by award999** [comment]
Reopened as #1316
