### ISSUE TITLE
Flaky Test Explorer test in CI

### ISSUE THREAD

**Issue by award999** [swiftlang/vscode-swift#1260]
Seen this fail in CI and locally
```
  1 failing
  1) Test Explorer Suite
       Standard
         Run Tests (Parallel)
           XCTests (Run Tests (Parallel))
             Runs failing test:

      AssertionError [ERR_ASSERTION]: Expected values to be loosely deep-equal:

{
  errored: [],
  failed: [
    {
      issues: [
        'Failed'
      ],
      test: 'PackageTests.FailingXCTestSuite/testFailing'
    },
    {
      issues: [],
      test: 'PackageTests.FailingXCTestSuite'
    }
  ],
  passed: [],
  skipped: [],
  unknown: 0
}

should loosely deep-equal

{
  errored: [],
  failed: [
    {
      issues: [
        'failed - oh no'
      ],
      test: 'PackageTests.FailingXCTestSuite/testFailing'
    },
    {
      issues: [],
      test: 'PackageTests.FailingXCTestSuite'
    }
  ],
  passed: [],
  skipped: [],
  unknown: 0
}
      + expected - actual

         "errored": []
         "failed": [
           {
             "issues": [
      -        "Failed"
      +        "failed - oh no"
             ]
             "test": "PackageTests.FailingXCTestSuite/testFailing"
           }
           {
      
      at assertTestResults (test/integration-tests/testexplorer/utilities.ts:137:12)
      at Context.<anonymous> (test/integration-tests/testexplorer/TestExplorerIntegration.test.ts:702:42)

1 test failed.
```

**Comment by award999** [comment]
Definitely not consistent :/
