### ISSUE TITLE
Running XCTest multiple times test fails nightly

### ISSUE THREAD

**Issue by award999** [swiftlang/vscode-swift#1262]
Failed in last night's nightly https://github.com/swiftlang/vscode-swift/actions/runs/12267257834/job/34227011961
```
  2) Test Explorer Suite
       Standard
         XCTest
           Runs multiple
             @slow runs an XCTest multiple times:
     AssertionError [ERR_ASSERTION]: Unable to find PackageTests.topLevelTestPassing() in Test Controller. Items in test controller are: PackageTests: PackageTests 
      at /tmp/code/test/integration-tests/testexplorer/utilities.ts:253:20
      at Array.map (<anonymous>)
      at gatherTests (test/integration-tests/testexplorer/utilities.ts:239:29)
      at Context.<anonymous> (test/integration-tests/testexplorer/TestExplorerIntegration.test.ts:450:56)
      at processImmediate (node:internal/timers:483:21)
```

**Comment by award999** [comment]
Looks fixed now https://github.com/swiftlang/vscode-swift/actions/runs/12299327001
