### ISSUE TITLE
Debugging tests failing on Windows with nightly-6.0 toolchain

### ISSUE THREAD

**Issue by award999** [swiftlang/vscode-swift#1263]
Any tests that use lldb are failing in the nightly build but only on Windows with the nightly-6.0 toolchain https://github.com/swiftlang/vscode-swift/actions/runs/12267257834/job/34227013218

**Comment by rbenegal** [comment]
Confirmed that the lldb tests now pass successfully locally and on github actions.


<details>
  <summary>
    Output from a local runs of lldb.test.ts and TestExplorerIntegration tests
  </summary>

```
 swift -v
Swift version 6.0.3 (swift-6.0.3-RELEASE)
Target: x86_64-unknown-windows-msvc
C:\Users\rishi\AppData\Local\Programs\Swift\Toolchains\6.0.3+Asserts\usr\bin\swift-help.exe intro
```
on  `vscode 1.96.4` with `Windows 11 24H2`

lldb.test.ts:
```
npm test -- --label integrationTests

> swift-lang@1.11.4 pretest
> npm run compile-tests


> swift-lang@1.11.4 compile-tests
> del-cli ./assets/test/**/.build && npm run compile


> swift-lang@1.11.4 compile
> del-cli ./dist/ && tsc --build


> swift-lang@1.11.4 test
> vscode-test --label integrationTests

✔ Validated version: 1.96.4
✔ Found existing install in C:\Users\rishi\src\vscode-swift\.vscode-test\vscode-win32-arm64-archive-1.96.4
✔ Validated version: 1.96.4
✔ Found existing install in C:\Users\rishi\src\vscode-swift\.vscode-test\vscode-win32-arm64-archive-1.96.4

...
  lldb contract test suite
13:42:10: Activating Swift for Visual Studio Code...
rejected promise not handled within 1 second: Error: This platform (win32-arm64) is not suported.
stack trace: Error: This platform (win32-arm64) is not suported.
    at c:\Users\rishi\src\vscode-swift\.vscode-test\extensions\vadimcn.vscode-lldb-1.11.1\extension.js:1:24061
    at c:\Users\rishi\src\vscode-swift\.vscode-test\extensions\vadimcn.vscode-lldb-1.11.1\extension.js:1:23829
    at Object.t.ensurePlatformPackage (c:\Users\rishi\src\vscode-swift\.vscode-test\extensions\vadimcn.vscode-lldb-1.11.1\extension.js:1:26544)
13:42:12: SourceKit-LSP setup
13:42:12: focus: undefined
Timed out waiting for authentication provider to register
13:42:16: test/defaultPackage: add: c:\Users\rishi\src\vscode-swift\assets\test\defaultPackage
    ✔ getLldbProcess Contract Test, make sure the command returns
13:42:18: test/defaultPackage: remove: c:\Users\rishi\src\vscode-swift\assets\test\defaultPackage
13:42:20: Activating Swift for Visual Studio Code...
13:42:20: SourceKit-LSP setup
13:42:20: focus: undefined
13:42:21: test/defaultPackage: add: c:\Users\rishi\src\vscode-swift\assets\test\defaultPackage
    ✔ getLLDBLibPath Contract Test, make sure we can find lib LLDB
13:42:22: test/defaultPackage: remove: c:\Users\rishi\src\vscode-swift\assets\test\defaultPackage
  2 passing (14s)
[main 2025-01-17T18:42:24.269Z] Extension host with pid 4996 exited with code: 0, signal: unknown.
(node:3276) [DEP0168] DeprecationWarning: Uncaught N-API callback exception detected, please run node with option --force-node-api-uncaught-exceptions-policy=true to handle those exceptions properly.
Exit code:   0
```

TestExplorerTests:
```
 Test Explorer Suite
13:47:46: Activating Swift for Visual Studio Code...
13:47:47: SourceKit-LSP setup
13:47:47: focus: undefined
rejected promise not handled within 1 second: Error: This platform (win32-arm64) is not suported.
stack trace: Error: This platform (win32-arm64) is not suported.
    at c:\Users\rishi\src\vscode-swift\.vscode-test\extensions\vadimcn.vscode-lldb-1.11.1\extension.js:1:24061
    at c:\Users\rishi\src\vscode-swift\.vscode-test\extensions\vadimcn.vscode-lldb-1.11.1\extension.js:1:23829
    at Object.t.ensurePlatformPackage (c:\Users\rishi\src\vscode-swift\.vscode-test\extensions\vadimcn.vscode-lldb-1.11.1\extension.js:1:26544)
13:47:49: test/defaultPackage: add: c:\Users\rishi\src\vscode-swift\assets\test\defaultPackage
13:47:49: WARN: Adding package folder file:///c%3A/Users/rishi/src/vscode-swift/assets/test/defaultPackage twice
Timed out waiting for authentication provider to register
    Debugging
      lldb-dap
13:47:56: Exec Task: (test/defaultPackage) swift build --build-tests -Xlinker -debug:dwarf -Xswiftc -diagnostic-style=llvm -Xswiftc -DTEST_ARGUMENT_SET_VIA_TEST_BUILD_ARGUMENTS_SETTING
Failed to clean up attachment path: Error: ENOENT: no such file or directory, scandir 'c:\Users\rishi\src\vscode-swift\assets\test\defaultPackage\.build\attachments\2025-01-17_13-48-44'
        ✔ Debugs specified XCTest test (52157ms)
13:48:48: Exec Task: (test/defaultPackage) swift build --build-tests -Xlinker -debug:dwarf -Xswiftc -diagnostic-style=llvm -Xswiftc -DTEST_ARGUMENT_SET_VIA_TEST_BUILD_ARGUMENTS_SETTING
Invalid debug adapter: Error: Invalid debug adapter
    at vVt.p (vscode-file://vscode-app/c:/Users/rishi/src/vscode-swift/.vscode-test/vscode-win32-arm64-archive-1.96.4/resources/app/out/vs/workbench/workbench.desktop.main.js:748:95)
    at vVt.$acceptDAExit (vscode-file://vscode-app/c:/Users/rishi/src/vscode-swift/.vscode-test/vscode-win32-arm64-archive-1.96.4/resources/app/out/vs/workbench/workbench.desktop.main.js:748:35)
    at Odt.S (vscode-file://vscode-app/c:/Users/rishi/src/vscode-swift/.vscode-test/vscode-win32-arm64-archive-1.96.4/resources/app/out/vs/workbench/workbench.desktop.main.js:3144:41680)
    at Odt.Q (vscode-file://vscode-app/c:/Users/rishi/src/vscode-swift/.vscode-test/vscode-win32-arm64-archive-1.96.4/resources/app/out/vs/workbench/workbench.desktop.main.js:3144:41458)
    at Odt.M (vscode-file://vscode-app/c:/Users/rishi/src/vscode-swift/.vscode-test/vscode-win32-arm64-archive-1.96.4/resources/app/out/vs/workbench/workbench.desktop.main.js:3144:40546)
    at Odt.L (vscode-file://vscode-app/c:/Users/rishi/src/vscode-swift/.vscode-test/vscode-win32-arm64-archive-1.96.4/resources/app/out/vs/workbench/workbench.desktop.main.js:3144:39783)
    at oee.value (vscode-file://vscode-app/c:/Users/rishi/src/vscode-swift/.vscode-test/vscode-win32-arm64-archive-1.96.4/resources/app/out/vs/workbench/workbench.desktop.main.js:3144:38444)
    at x.B (vscode-file://vscode-app/c:/Users/rishi/src/vscode-swift/.vscode-test/vscode-win32-arm64-archive-1.96.4/resources/app/out/vs/workbench/workbench.desktop.main.js:30:748)
    at x.fire (vscode-file://vscode-app/c:/Users/rishi/src/vscode-swift/.vscode-test/vscode-win32-arm64-archive-1.96.4/resources/app/out/vs/workbench/workbench.desktop.main.js:30:967)
    at K6.fire (vscode-file://vscode-app/c:/Users/rishi/src/vscode-swift/.vscode-test/vscode-win32-arm64-archive-1.96.4/resources/app/out/vs/workbench/workbench.desktop.main.js:762:10348)
        ✔ Debugs specified swift-testing test (6783ms)
13:48:55: test/defaultPackage: remove: c:\Users\rishi\src\vscode-swift\assets\test\defaultPackage
Invalid debug adapter: Error: Invalid debug adapter
    at vVt.p (vscode-file://vscode-app/c:/Users/rishi/src/vscode-swift/.vscode-test/vscode-win32-arm64-archive-1.96.4/resources/app/out/vs/workbench/workbench.desktop.main.js:748:95)
    at vVt.$acceptDAExit (vscode-file://vscode-app/c:/Users/rishi/src/vscode-swift/.vscode-test/vscode-win32-arm64-archive-1.96.4/resources/app/out/vs/workbench/workbench.desktop.main.js:748:35)
    at Odt.S (vscode-file://vscode-app/c:/Users/rishi/src/vscode-swift/.vscode-test/vscode-win32-arm64-archive-1.96.4/resources/app/out/vs/workbench/workbench.desktop.main.js:3144:41680)
    at Odt.Q (vscode-file://vscode-app/c:/Users/rishi/src/vscode-swift/.vscode-test/vscode-win32-arm64-archive-1.96.4/resources/app/out/vs/workbench/workbench.desktop.main.js:3144:41458)
    at Odt.M (vscode-file://vscode-app/c:/Users/rishi/src/vscode-swift/.vscode-test/vscode-win32-arm64-archive-1.96.4/resources/app/out/vs/workbench/workbench.desktop.main.js:3144:40546)
    at Odt.L (vscode-file://vscode-app/c:/Users/rishi/src/vscode-swift/.vscode-test/vscode-win32-arm64-archive-1.96.4/resources/app/out/vs/workbench/workbench.desktop.main.js:3144:39783)
    at oee.value (vscode-file://vscode-app/c:/Users/rishi/src/vscode-swift/.vscode-test/vscode-win32-arm64-archive-1.96.4/resources/app/out/vs/workbench/workbench.desktop.main.js:3144:38444)
    at x.B (vscode-file://vscode-app/c:/Users/rishi/src/vscode-swift/.vscode-test/vscode-win32-arm64-archive-1.96.4/resources/app/out/vs/workbench/workbench.desktop.main.js:30:748)
    at x.fire (vscode-file://vscode-app/c:/Users/rishi/src/vscode-swift/.vscode-test/vscode-win32-arm64-archive-1.96.4/resources/app/out/vs/workbench/workbench.desktop.main.js:30:967)
    at K6.fire (vscode-file://vscode-app/c:/Users/rishi/src/vscode-swift/.vscode-test/vscode-win32-arm64-archive-1.96.4/resources/app/out/vs/workbench/workbench.desktop.main.js:762:10348)
  2 passing (1m)
[main 2025-01-17T18:48:57.490Z] Extension host with pid 10268 exited with code: 0, signal: unknown.
Exit code:   0
```
</details>

And passing in GitHub actions (https://github.com/swiftlang/vscode-swift/actions/runs/12820136815/job/35749179901):


<details>
<summary>
Output from TestExplorer and lldb.test suites
</summary>

```
Test Explorer Suite
    Debugging
      lldb-dap
        ✔ Debugs specified XCTest test (39400ms)
Invalid debug adapter: Error: Invalid debug adapter
    at vVt.p (vscode-file://vscode-app/d:/a/vscode-swift/vscode-swift/.vscode-test/vscode-win32-x64-archive-1.96.4/resources/app/out/vs/workbench/workbench.desktop.main.js:748:95)
    at vVt.$acceptDAExit (vscode-file://vscode-app/d:/a/vscode-swift/vscode-swift/.vscode-test/vscode-win32-x64-archive-1.96.4/resources/app/out/vs/workbench/workbench.desktop.main.js:748:35)
    at Odt.S (vscode-file://vscode-app/d:/a/vscode-swift/vscode-swift/.vscode-test/vscode-win32-x64-archive-1.96.4/resources/app/out/vs/workbench/workbench.desktop.main.js:3144:41680)
    at Odt.Q (vscode-file://vscode-app/d:/a/vscode-swift/vscode-swift/.vscode-test/vscode-win32-x64-archive-1.96.4/resources/app/out/vs/workbench/workbench.desktop.main.js:3144:41458)
    at Odt.M (vscode-file://vscode-app/d:/a/vscode-swift/vscode-swift/.vscode-test/vscode-win32-x64-archive-1.96.4/resources/app/out/vs/workbench/workbench.desktop.main.js:3144:40546)
    at Odt.L (vscode-file://vscode-app/d:/a/vscode-swift/vscode-swift/.vscode-test/vscode-win32-x64-archive-1.96.4/resources/app/out/vs/workbench/workbench.desktop.main.js:3144:39783)
    at oee.value (vscode-file://vscode-app/d:/a/vscode-swift/vscode-swift/.vscode-test/vscode-win32-x64-archive-1.96.4/resources/app/out/vs/workbench/workbench.desktop.main.js:3144:38444)
    at x.B (vscode-file://vscode-app/d:/a/vscode-swift/vscode-swift/.vscode-test/vscode-win32-x64-archive-1.96.4/resources/app/out/vs/workbench/workbench.desktop.main.js:30:748)
    at x.fire (vscode-file://vscode-app/d:/a/vscode-swift/vscode-swift/.vscode-test/vscode-win32-x64-archive-1.96.4/resources/app/out/vs/workbench/workbench.desktop.main.js:30:967)
    at K6.fire (vscode-file://vscode-app/d:/a/vscode-swift/vscode-swift/.vscode-test/vscode-win32-x64-archive-1.96.4/resources/app/out/vs/workbench/workbench.desktop.main.js:762:10348)
Invalid debug adapter: Error: Invalid debug adapter
        ✔ Debugs specified swift-testing test
    at vVt.p (vscode-file://vscode-app/d:/a/vscode-swift/vscode-swift/.vscode-test/vscode-win32-x64-archive-1.96.4/resources/app/out/vs/workbench/workbench.desktop.main.js:748:95)
    at vVt.$acceptDAExit (vscode-file://vscode-app/d:/a/vscode-swift/vscode-swift/.vscode-test/vscode-win32-x64-archive-1.96.4/resources/app/out/vs/workbench/workbench.desktop.main.js:748:35)
    at Odt.S (vscode-file://vscode-app/d:/a/vscode-swift/vscode-swift/.vscode-test/vscode-win32-x64-archive-1.96.4/resources/app/out/vs/workbench/workbench.desktop.main.js:3144:41680)
    at Odt.Q (vscode-file://vscode-app/d:/a/vscode-swift/vscode-swift/.vscode-test/vscode-win32-x64-archive-1.96.4/resources/app/out/vs/workbench/workbench.desktop.main.js:3144:41458)
    at Odt.M (vscode-file://vscode-app/d:/a/vscode-swift/vscode-swift/.vscode-test/vscode-win32-x64-archive-1.96.4/resources/app/out/vs/workbench/workbench.desktop.main.js:3144:40546)
    at Odt.L (vscode-file://vscode-app/d:/a/vscode-swift/vscode-swift/.vscode-test/vscode-win32-x64-archive-1.96.4/resources/app/out/vs/workbench/workbench.desktop.main.js:3144:39783)
    at oee.value (vscode-file://vscode-app/d:/a/vscode-swift/vscode-swift/.vscode-test/vscode-win32-x64-archive-1.96.4/resources/app/out/vs/workbench/workbench.desktop.main.js:3144:38444)
    at x.B (vscode-file://vscode-app/d:/a/vscode-swift/vscode-swift/.vscode-test/vscode-win32-x64-archive-1.96.4/resources/app/out/vs/workbench/workbench.desktop.main.js:30:748)
    at x.fire (vscode-file://vscode-app/d:/a/vscode-swift/vscode-swift/.vscode-test/vscode-win32-x64-archive-1.96.4/resources/app/out/vs/workbench/workbench.desktop.main.js:30:967)
    at K6.fire (vscode-file://vscode-app/d:/a/vscode-swift/vscode-swift/.vscode-test/vscode-win32-x64-archive-1.96.4/resources/app/out/vs/workbench/workbench.desktop.main.js:762:10348)
      CodeLLDB
        - Debugs specified XCTest test
        - Debugs specified swift-testing test
```

```
lldb contract test suite
    ✔ getLldbProcess Contract Test, make sure the command returns
    ✔ getLLDBLibPath Contract Test, make sure we can find lib LLDB
```

</details>
