### ISSUE TITLE
Build Commands suite is flaky

### ISSUE THREAD

**Issue by award999** [swiftlang/vscode-swift#1269]
Flaking in nightly build https://github.com/award999/vscode-swift/actions/runs/12287793290/job/34290458188
```
  2) Build Commands
       Swift: Debug Build @slow:
     Error: Timeout of 30000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/tmp/code/dist/test/integration-tests/commands/build.test.js)
```

**Comment by rbenegal** [comment]
Confirmed that the `Build Commands` tests now pass successfully locally and on github actions. It does seem like they spew out a whole bench of errors which may be confusing, possibly we can clean this up them later.


<details>
  <summary>
    Output from a local run of build.test.ts on linux
  </summary>

```
 swift -v
Swift version 6.0.3 (swift-6.0.3-RELEASE)
```
on  `vscode 1.96.4` with `Ubuntu 22.04`

build.test.ts:
```
npm test -- --label integrationTests

> swift-lang@1.11.4 pretest
> npm run compile-tests


> swift-lang@1.11.4 compile-tests
> del-cli ./assets/test/**/.build && npm run compile


> swift-lang@1.11.4 compile
> del-cli ./dist/ && tsc --build


> swift-lang@1.11.4 test
> vscode-test --label integrationTests

✔ Validated version: 1.96.4
✔ Found existing install in /home/rishi/src/vscode-swift/.vscode-test/vscode-linux-arm64-1.96.4
✔ Validated version: 1.96.4
✔ Found existing install in /home/rishi/src/vscode-swift/.vscode-test/vscode-linux-arm64-1.96.4
[main 2025-01-20T15:51:04.146Z] update#setState disabled
[main 2025-01-20T15:51:04.149Z] update#ctor - updates are disabled by the environment
Via 'product.json#extensionEnabledApiProposals' extension 'ms-vscode.vscode-selfhost-test-provider' wants API proposal 'attributableCoverage' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
Via 'product.json#extensionEnabledApiProposals' extension 'ms-python.python' wants API proposal 'contribIssueReporter' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
Via 'product.json#extensionEnabledApiProposals' extension 'ms-python.debugpy' wants API proposal 'contribIssueReporter' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
Started local extension host with pid 15642.
Loading development extension at /home/rishi/src/vscode-swift
Settings Sync: Account status changed from uninitialized to unavailable

  Build Commands @slow
10:51:07: Activating Swift for Visual Studio Code...
10:51:07: SourceKit-LSP setup
10:51:07: focus: undefined
10:51:09: test/defaultPackage: add: /home/rishi/src/vscode-swift/assets/test/defaultPackage
10:51:09: WARN: Adding package folder file:///home/rishi/src/vscode-swift/assets/test/defaultPackage twice
10:51:09: unfocus: undefined
10:51:09: test/defaultPackage: focus: /home/rishi/src/vscode-swift/assets/test/defaultPackage
Timed out waiting for authentication provider to register
    ✔ Swift: Run Build (8351ms)
Invalid debug adapter: Error: Invalid debug adapter
    at vVt.p (vscode-file://vscode-app/home/rishi/src/vscode-swift/.vscode-test/vscode-linux-arm64-1.96.4/resources/app/out/vs/workbench/workbench.desktop.main.js:748:95)
    at vVt.$acceptDAExit (vscode-file://vscode-app/home/rishi/src/vscode-swift/.vscode-test/vscode-linux-arm64-1.96.4/resources/app/out/vs/workbench/workbench.desktop.main.js:748:35)
    at Odt.S (vscode-file://vscode-app/home/rishi/src/vscode-swift/.vscode-test/vscode-linux-arm64-1.96.4/resources/app/out/vs/workbench/workbench.desktop.main.js:3144:41680)
    at Odt.Q (vscode-file://vscode-app/home/rishi/src/vscode-swift/.vscode-test/vscode-linux-arm64-1.96.4/resources/app/out/vs/workbench/workbench.desktop.main.js:3144:41458)
    at Odt.M (vscode-file://vscode-app/home/rishi/src/vscode-swift/.vscode-test/vscode-linux-arm64-1.96.4/resources/app/out/vs/workbench/workbench.desktop.main.js:3144:40546)
    at Odt.L (vscode-file://vscode-app/home/rishi/src/vscode-swift/.vscode-test/vscode-linux-arm64-1.96.4/resources/app/out/vs/workbench/workbench.desktop.main.js:3144:39783)
    at oee.value (vscode-file://vscode-app/home/rishi/src/vscode-swift/.vscode-test/vscode-linux-arm64-1.96.4/resources/app/out/vs/workbench/workbench.desktop.main.js:3144:38444)
    at x.B (vscode-file://vscode-app/home/rishi/src/vscode-swift/.vscode-test/vscode-linux-arm64-1.96.4/resources/app/out/vs/workbench/workbench.desktop.main.js:30:748)
    at x.fire (vscode-file://vscode-app/home/rishi/src/vscode-swift/.vscode-test/vscode-linux-arm64-1.96.4/resources/app/out/vs/workbench/workbench.desktop.main.js:30:967)
    at K6.fire (vscode-file://vscode-app/home/rishi/src/vscode-swift/.vscode-test/vscode-linux-arm64-1.96.4/resources/app/out/vs/workbench/workbench.desktop.main.js:762:10348)
10:51:19: test/defaultPackage: Clean Build: starting ... 
10:51:19: Exec Task: (test/defaultPackage) swift package clean
Invalid debug adapter: Error: Invalid debug adapter
    at vVt.p (vscode-file://vscode-app/home/rishi/src/vscode-swift/.vscode-test/vscode-linux-arm64-1.96.4/resources/app/out/vs/workbench/workbench.desktop.main.js:748:95)
    at vVt.$acceptDAExit (vscode-file://vscode-app/home/rishi/src/vscode-swift/.vscode-test/vscode-linux-arm64-1.96.4/resources/app/out/vs/workbench/workbench.desktop.main.js:748:35)
    at Odt.S (vscode-file://vscode-app/home/rishi/src/vscode-swift/.vscode-test/vscode-linux-arm64-1.96.4/resources/app/out/vs/workbench/workbench.desktop.main.js:3144:41680)
    at Odt.Q (vscode-file://vscode-app/home/rishi/src/vscode-swift/.vscode-test/vscode-linux-arm64-1.96.4/resources/app/out/vs/workbench/workbench.desktop.main.js:3144:41458)
    at Odt.M (vscode-file://vscode-app/home/rishi/src/vscode-swift/.vscode-test/vscode-linux-arm64-1.96.4/resources/app/out/vs/workbench/workbench.desktop.main.js:3144:40546)
    at Odt.L (vscode-file://vscode-app/home/rishi/src/vscode-swift/.vscode-test/vscode-linux-arm64-1.96.4/resources/app/out/vs/workbench/workbench.desktop.main.js:3144:39783)
    at oee.value (vscode-file://vscode-app/home/rishi/src/vscode-swift/.vscode-test/vscode-linux-arm64-1.96.4/resources/app/out/vs/workbench/workbench.desktop.main.js:3144:38444)
    at x.B (vscode-file://vscode-app/home/rishi/src/vscode-swift/.vscode-test/vscode-linux-arm64-1.96.4/resources/app/out/vs/workbench/workbench.desktop.main.js:30:748)
    at x.fire (vscode-file://vscode-app/home/rishi/src/vscode-swift/.vscode-test/vscode-linux-arm64-1.96.4/resources/app/out/vs/workbench/workbench.desktop.main.js:30:967)
    at K6.fire (vscode-file://vscode-app/home/rishi/src/vscode-swift/.vscode-test/vscode-linux-arm64-1.96.4/resources/app/out/vs/workbench/workbench.desktop.main.js:762:10348)
10:51:20: test/defaultPackage: Clean Build: ... done.
    ✔ Swift: Clean Build
    ✔ Swift: Debug Build
10:51:23: test/defaultPackage: unfocus: /home/rishi/src/vscode-swift/assets/test/defaultPackage
10:51:23: test/defaultPackage: remove: /home/rishi/src/vscode-swift/assets/test/defaultPackage
10:51:23: focus: undefined
  3 passing (18s)
[main 2025-01-20T15:51:24.871Z] Extension host with pid 15642 exited with code: 0, signal: unknown.
Exit code:   0
```
</details>

And passing in GitHub actions (https://github.com/swiftlang/vscode-swift/actions/runs/12848727861/job/35826444679):

<details>
<summary>
Output from build.test.ts
</summary>

```
    Build Commands @slow
    ✔ Swift: Run Build
Invalid debug adapter: Error: Invalid debug adapter
    at vVt.p (vscode-file://vscode-app/tmp/code/.vscode-test/vscode-linux-x64-1.96.4/resources/app/out/vs/workbench/workbench.desktop.main.js:748:95)
    at vVt.$acceptDAExit (vscode-file://vscode-app/tmp/code/.vscode-test/vscode-linux-x64-1.96.4/resources/app/out/vs/workbench/workbench.desktop.main.js:748:35)
    at Odt.S (vscode-file://vscode-app/tmp/code/.vscode-test/vscode-linux-x64-1.96.4/resources/app/out/vs/workbench/workbench.desktop.main.js:3144:41680)
    at Odt.Q (vscode-file://vscode-app/tmp/code/.vscode-test/vscode-linux-x64-1.96.4/resources/app/out/vs/workbench/workbench.desktop.main.js:3144:41458)
    at Odt.M (vscode-file://vscode-app/tmp/code/.vscode-test/vscode-linux-x64-1.96.4/resources/app/out/vs/workbench/workbench.desktop.main.js:3144:40546)
    at Odt.L (vscode-file://vscode-app/tmp/code/.vscode-test/vscode-linux-x64-1.96.4/resources/app/out/vs/workbench/workbench.desktop.main.js:3144:39783)
    at oee.value (vscode-file://vscode-app/tmp/code/.vscode-test/vscode-linux-x64-1.96.4/resources/app/out/vs/workbench/workbench.desktop.main.js:3144:38444)
    at x.B (vscode-file://vscode-app/tmp/code/.vscode-test/vscode-linux-x64-1.96.4/resources/app/out/vs/workbench/workbench.desktop.main.js:30:748)
    at x.fire (vscode-file://vscode-app/tmp/code/.vscode-test/vscode-linux-x64-1.96.4/resources/app/out/vs/workbench/workbench.desktop.main.js:30:967)
    at K6.fire (vscode-file://vscode-app/tmp/code/.vscode-test/vscode-linux-x64-1.96.4/resources/app/out/vs/workbench/workbench.desktop.main.js:762:10348)
Invalid debug adapter: Error: Invalid debug adapter
    at vVt.p (vscode-file://vscode-app/tmp/code/.vscode-test/vscode-linux-x64-1.96.4/resources/app/out/vs/workbench/workbench.desktop.main.js:748:95)
    at vVt.$acceptDAExit (vscode-file://vscode-app/tmp/code/.vscode-test/vscode-linux-x64-1.96.4/resources/app/out/vs/workbench/workbench.desktop.main.js:748:35)
    at Odt.S (vscode-file://vscode-app/tmp/code/.vscode-test/vscode-linux-x64-1.96.4/resources/app/out/vs/workbench/workbench.desktop.main.js:3144:41680)
    at Odt.Q (vscode-file://vscode-app/tmp/code/.vscode-test/vscode-linux-x64-1.96.4/resources/app/out/vs/workbench/workbench.desktop.main.js:3144:41458)
    at Odt.M (vscode-file://vscode-app/tmp/code/.vscode-test/vscode-linux-x64-1.96.4/resources/app/out/vs/workbench/workbench.desktop.main.js:3144:40546)
    at Odt.L (vscode-file://vscode-app/tmp/code/.vscode-test/vscode-linux-x64-1.96.4/resources/app/out/vs/workbench/workbench.desktop.main.js:3144:39783)
    at oee.value (vscode-file://vscode-app/tmp/code/.vscode-test/vscode-linux-x64-1.96.4/resources/app/out/vs/workbench/workbench.desktop.main.js:3144:38444)
    at x.B (vscode-file://vscode-app/tmp/code/.vscode-test/vscode-linux-x64-1.96.4/resources/app/out/vs/workbench/workbench.desktop.main.js:30:748)
    at x.fire (vscode-file://vscode-app/tmp/code/.vscode-test/vscode-linux-x64-1.96.4/resources/app/out/vs/workbench/workbench.desktop.main.js:30:967)
    at K6.fire (vscode-file://vscode-app/tmp/code/.vscode-test/vscode-linux-x64-1.96.4/resources/app/out/vs/workbench/workbench.desktop.main.js:762:10348)
    ✔ Swift: Clean Build
    ✔ Swift: Debug Build

```

</details>
